/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

/**
 *
 * @author adria
 */

import Model.Concesionario;
import Model.Extra;
import Model.Modelo;
public class AppConcesionarioUI extends javax.swing.JFrame {

    /**
     * Creates new form AppMainForm
     */
    public AppConcesionarioUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        signinButton = new javax.swing.JButton();
        pedidosButton = new javax.swing.JButton();
        modelList = new java.awt.List();
        catalogoButton = new javax.swing.JButton();
        modelDetails = new java.awt.List();
        comentariosList = new java.awt.List();
        DetailsLabel = new javax.swing.JLabel();
        ComentsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comentarioTextBox = new javax.swing.JTextField();
        comentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(706, 384));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(706, 384));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setText("Iniciar Sesión");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        Background.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 6, -1, -1));

        signinButton.setText("Registrarse");
        signinButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinButtonMouseClicked(evt);
            }
        });
        signinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinButtonActionPerformed(evt);
            }
        });
        Background.add(signinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 6, 77, -1));

        pedidosButton.setText("Pedidos");
        pedidosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosButtonActionPerformed(evt);
            }
        });
        Background.add(pedidosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 6, 57, -1));

        modelList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelListActionPerformed(evt);
            }
        });
        Background.add(modelList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 248, 312));

        catalogoButton.setText("Mostrar Catalogo");
        catalogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoButtonActionPerformed(evt);
            }
        });
        Background.add(catalogoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, 248, -1));

        modelDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelDetailsActionPerformed(evt);
            }
        });
        Background.add(modelDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 62, 168, 122));
        Background.add(comentariosList, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 216, 168, 158));

        DetailsLabel.setForeground(new java.awt.Color(0, 0, 0));
        DetailsLabel.setText("Detalles");
        Background.add(DetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 32, 84, -1));

        ComentsLabel.setForeground(new java.awt.Color(0, 0, 0));
        ComentsLabel.setText("Comentarios");
        Background.add(ComentsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 190, 84, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Información de contacto");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 180, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Telefono: 928 13 54 60");
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 220, 30));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mail: concesionariopaco@gmail.com");
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 220, -1));

        comentarioTextBox.setText("Comentario");
        Background.add(comentarioTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 140, -1));

        comentButton.setText("Añadir comentario");
        comentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comentButtonActionPerformed(evt);
            }
        });
        Background.add(comentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        if(Concesionario.getClienteActual() == null){
            loginButton.setVisible(true);
        }else{
            loginButton.setVisible(false);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        new LogInForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginButtonMouseClicked

    private void signinButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinButtonMouseClicked
        // TODO add your handling code here:
        new SignInForm().setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_signinButtonMouseClicked

    private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
        // TODO add your handling code here:
         if(Concesionario.getClienteActual() == null){
            signinButton.setVisible(true);
        }else{
            signinButton.setVisible(false);
        }
    }//GEN-LAST:event_signinButtonActionPerformed

    private void pedidosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosButtonActionPerformed
        //HAcer q no aparezca hasta haber iniciado sesion
        Pedidos ventanaPedidos = new Pedidos();
        ventanaPedidos.showModelList();
        ventanaPedidos.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_pedidosButtonActionPerformed

    private void modelListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelListActionPerformed
        // TODO add your handling code here:
        showModelDetails(Concesionario.getModelos().get(modelList.getSelectedIndex()));
        showModelComents(Concesionario.getModelos().get(modelList.getSelectedIndex()));
    }//GEN-LAST:event_modelListActionPerformed

    private void catalogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoButtonActionPerformed
        // TODO add your handling code here:
        showModelList();
    }//GEN-LAST:event_catalogoButtonActionPerformed

    private void modelDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelDetailsActionPerformed

    private void comentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comentButtonActionPerformed
        // TODO add your handling code here:
        String comentario = comentarioTextBox.getText();
        String autor = Concesionario.getClienteActual().getDni();
        Modelo modelo = Concesionario.getModelos().get(modelList.getSelectedIndex());
        modelo.addComentario(comentario, autor);
    }//GEN-LAST:event_comentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppConcesionarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppConcesionarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppConcesionarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppConcesionarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppConcesionarioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel ComentsLabel;
    private javax.swing.JLabel DetailsLabel;
    private javax.swing.JButton catalogoButton;
    private javax.swing.JButton comentButton;
    private javax.swing.JTextField comentarioTextBox;
    private java.awt.List comentariosList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private java.awt.List modelDetails;
    private java.awt.List modelList;
    private javax.swing.JButton pedidosButton;
    private javax.swing.JButton signinButton;
    // End of variables declaration//GEN-END:variables

    private void showModelDetails(Modelo modelo) {
        modelDetails.add(modelo.getNombre());
        modelDetails.add(String.valueOf(modelo.getIdModelo()));
        modelDetails.add(String.valueOf(modelo.getPrecioBase()));
        Extra extra;
        for(int i = 0; i< modelo.getExtrasDisponibles().size();i++){
           extra = modelo.getExtrasDisponibles().get(i);
           modelDetails.add(extra.getNombre());
        }
    }

    private void showModelList() {
        int i;
        modelList.removeAll();
        for(i=0;i < Concesionario.getModelos().size();i++)
            modelList.add(Concesionario.getModelos().get(i).getNombre());
    }

    private void showModelComents(Modelo modelo) {
        comentariosList.removeAll();
        for (int i = 0; i < modelo.getComentarios().size() ; i++) {
            comentariosList.add(modelo.getComentarios().get(i).getAutorDni());
            comentariosList.add(modelo.getComentarios().get(i).getComentario());
        }
    }
}
